### ISSUE TITLE
blue on black questionmark

### ISSUE THREAD

**Issue by sebs** [sumcumo/lighthouse-keeper#8]
maybe  change the blue to green to make it a bit better recognizable.

**Comment by svewag** [comment]
Hey @sebs,

thanks for your feedback.

Can you provide a screenshot? I think the specific color depend on your terminal settings, because we are using `chalk` and no specific color codes. 🤔

**Comment by sebs** [comment]
On Linux: Only questionmark, on mac it comes with a round border.

**Comment by sebs** [comment]
<img width="245" alt="bildschirmfoto 2018-12-13 um 15 31 07" src="https://user-images.githubusercontent.com/55102/49945041-2d447c00-feec-11e8-9786-2d8193965ec4.png">
There is a mac example

**Comment by sebs** [comment]
mac + zsh

**Comment by sebs** [comment]
my linux has no zsh but a blue questionmark w.o. Border.
