### ISSUE TITLE
`onlyCategories` vs `onlyAudits`

### ISSUE THREAD

**Issue by mstruebing** [sumcumo/lighthouse-keeper#9]
While scanning the readme I've found  that one time `onlyAudits` are mentioned for the configuration and another time it is called `onlyCategories`.

`onlyCategories`: https://github.com/sumcumo/lighthouse-keeper/blob/master/README.md#example
`onlyAudits`: https://github.com/sumcumo/lighthouse-keeper/blob/master/README.md#options

I think that they are both the same and it is just a leftover after a namechange.

**Comment by j9t** [comment]
Thanks @mstruebing! From scanning the docs it seems to me that `onlyCategories` is correct and intended (and that they are different from the audits), but that the options we list in our documentation are indeed inaccurate. @svewag, do you mind having a look? (I can probably check again later, too.)

**Comment by j9t** [comment]
Can’t comment on all the `onlyAudits` but the config breaks now—rolling back with the config mod with https://github.com/sumcumo/lighthouse-keeper/pull/12.
